### ISSUE TITLE
Add a footer

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-22.P3.2-portfolio#1]
Add a footer that acts a site map, and includes some information about the pod, such as:

- Blog
- About
- Socials
- Projects

**Comment by prakharrathi25** [comment]
Can @arteevraina and I take this issue? I am done with my previous PR. Please let me know if someone else is working on it.

**Comment by 2001asjad** [comment]
Hi @prakharrathi25 I am working on it along with my teammate .

**Comment by 2001asjad** [comment]
Hey @prakharrathi25 , me and my teammate are working on this issue.

**Comment by prakharrathi25** [comment]
Hey, yeah I missed that message where it was assigned to you. My bad. Best of luck with the issue!
