### ISSUE TITLE
Add a map showing all the countries that fellows are located in

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-22.P3.2-portfolio#10]
Underneath projects and fellows, have an interactive map that displays where everyone is located.

- [ ] When you click on the pin location for that fellow, it gives you a card with information about the fellow (similar to the fellow section

You can chose to have pins or use circular profile pictures to show where everyone is on the map. You could remove the fellows section and replace it with the map.

**Comment by yahya-cloud** [comment]
can me and @RishiDesai17 take this issue. Please let us know if someone else is also working on this issue

**Comment by prakharrathi25** [comment]
I would love to work with you on this issue.

**Comment by marcnjaramillo** [comment]
The map is currently not loading on the page. Could you look into this and see what's going on?
