### ISSUE TITLE
Add social icons for fellows

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-22.P3.2-portfolio#11]
At the moment, it only displays the fellow name and location. To help people network, we should add social icons to each of the fellow cards.

![Screenshot 2021-09-30 at 14 24 40](https://user-images.githubusercontent.com/34094921/135463524-d5ddd708-920c-4fc0-ba87-02ca80186d9e.png)
- [ ] Add LinkedIn icons to the card
- [ ] Add Twitter icons to the card
- [ ] Add Resume icons to the card
- [ ] Add GitHub icons to the card

**Comment by prakharrathi25** [comment]
Hi, 

Could @arteevraina and I work on this issue? Please let me know if someone else has already taken it?

**Comment by prakharrathi25** [comment]
This issue is closely connected to #13 as well so I am wondering if we could deal with both of those together. I am almost done working on this issue.

**Comment by prakharrathi25** [comment]
I just saw that #13 is assigned to @Mitali-laroia and @samarthya-jha. I am actually pushing a change to the `fellows.yml` file which might lead to conflict with your pull request. Could you pull these changes first or reach out to me or @arteevraina to discuss the changes before you make your PR? Thanks!
