### ISSUE TITLE
UI needs to be fixed: scrollToTop button needs to be moved

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/pod-22.P3.2-portfolio#28]
# Issue
There is an issue with where the `scrollToTop` arrow is located:

<img width="1440" alt="Screen Shot 2022-04-06 at 10 15 57 AM" src="https://user-images.githubusercontent.com/18270672/162033553-33df7766-0002-4a86-94c1-0a868a9e8906.png">

It currently sits at the top of the page above the header, so it is taking up space from the top of the page which causes the navbar to be displaced:

<img width="1440" alt="Screen Shot 2022-04-06 at 10 17 25 AM" src="https://user-images.githubusercontent.com/18270672/162033568-88b5080c-fb81-4dcc-9413-e33c1667d178.png">

# Proposed Solution

- Move the `scrollToTop` element to the bottom of the page above the footer.
- Use CSS `position` properties to keep the arrow positioned in the bottom corner (left or right) until the user scrolls to the bottom of the page, where it should sit just above the footer.

**Comment by prakharrathi25** [comment]
I would like to work on this issue.

**Comment by marcnjaramillo** [comment]
You've got it. Let me know if you and your team need help!
