### ISSUE TITLE
Fix navbar link href properties

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/pod-22.P3.2-portfolio#29]
# Problem
Currently, clicking on the navbar links for "Meet the Pod" positions the container awkwardly, forcing users to manually scroll up to the top of the container. This is because the `href` property points to the `id` of the container itself, rather than the heading:

<img width="826" alt="Screen Shot 2022-04-06 at 10 45 22 AM" src="https://user-images.githubusercontent.com/18270672/162036230-36235075-c1c5-4267-9720-d4fe8d9a1f97.png">

# Proposed Solution
Add an `id` to the headings of each section called "[section]-nav" and point the `href` of the nav links to this `id`. Additionally, add some padding to the top of the containers to provide a little space between the navbar and the container when it scrolls.

**Comment by RishiDesai17** [comment]
@marcnjaramillo I would like to make this change

**Comment by marcnjaramillo** [comment]
You got it

**Comment by RishiDesai17** [comment]
@marcnjaramillo Instead of adding some padding, I used a pseudo element on the sections to manage this, so that we don't need to create extra space and we still get proper anchor navigation.
