### ISSUE TITLE
Add navbar and footer to individual project and blog page

### ISSUE THREAD

**Issue by prakharrathi25** [MLH-Fellowship/pod-22.P3.2-portfolio#33]
Right now there is no navbar or footer in the individual project page or blog page. It is difficult to return to home page from there. Once the navbar is finalized, it should be added to these pages as well. Image of current page shown below. 

<img width="610" alt="image" src="https://user-images.githubusercontent.com/38958532/162071619-90e942b2-9742-4ea2-9691-c46d854734ba.png">

Link to this page: https://prep-22-p3-2.netlify.app/projects/project

**Comment by arteevraina** [comment]
Hey @prakharrathi25 ! I think this has been added check here. https://prep-22-p3-2.netlify.app/#projects-nav

**Comment by prakharrathi25** [comment]
> Hey @prakharrathi25 ! I think this has been added check here. [prep-22-p3-2.netlify.app/#projects-nav](https://prep-22-p3-2.netlify.app/#projects-nav)

There is no navbar on these pages though. If we don't need it then I will close the issue.

**Comment by arteevraina** [comment]
> > Hey @prakharrathi25 ! I think this has been added check here. [prep-22-p3-2.netlify.app/#projects-nav](https://prep-22-p3-2.netlify.app/#projects-nav)
> 
> There is no navbar on these pages though. If we don't need it then I will close the issue.

My bad I just read footer in the issue title. Yes, I think we need it help us easily navigate to homepage.

**Comment by marcnjaramillo** [comment]
There is no navbar needed on these pages, but in mobile view the theme toggle should still be visible. Also, the mobile navigation icon still shows on smaller screens, which is a bug.

<img width="298" alt="Screen Shot 2022-04-11 at 8 48 38 AM" src="https://user-images.githubusercontent.com/18270672/162780159-c45218d7-3099-434c-b5dd-cadc463694a8.png">

<img width="300" alt="Screen Shot 2022-04-11 at 8 48 50 AM" src="https://user-images.githubusercontent.com/18270672/162780173-2e681681-824c-402f-b917-94b13f25b249.png">

**Comment by RishiDesai17** [comment]
@marcnjaramillo Works fine for me on Chrome.
![image](https://user-images.githubusercontent.com/51089917/162781930-545b24dd-982b-45d9-b1ed-4fa745f7a87a.png)
![image](https://user-images.githubusercontent.com/51089917/162781987-b5c18c1b-26d4-4570-ab8a-e0dc5ad31b50.png)
