### ISSUE TITLE
Bug: Navbar picture not in sync with the dark mode toggle

### ISSUE THREAD

**Issue by prakharrathi25** [MLH-Fellowship/pod-22.P3.2-portfolio#37]
This is a minor UI issue but the dark mode toggle button is not in the same row as the navbar logo. This could be fixed to make the UI better.

<img width="922" alt="image" src="https://user-images.githubusercontent.com/38958532/162135297-1ecb5590-74a6-4911-82c6-8a1d14e47051.png">

**Comment by marcnjaramillo** [comment]
I believe this has been resolved by PR [#41](https://github.com/MLH-Fellowship/pod-22.P3.2-portfolio/pull/41), so we can close this.
