### ISSUE TITLE
Update footer styles

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/pod-22.P3.2-portfolio#38]
# Problem
Everything is looking really good, but the footer could be updated to match the styles of the rest of the project:

<img width="1434" alt="Screen Shot 2022-04-06 at 11 30 47 PM" src="https://user-images.githubusercontent.com/18270672/162134681-3a863260-5231-4f9e-9de5-d18dc26f5b1b.png">

This is related to another issue with text color being too close to the background color in dark mode:

<img width="1433" alt="Screen Shot 2022-04-06 at 11 34 05 PM" src="https://user-images.githubusercontent.com/18270672/162135112-dd9661db-d808-4deb-bb4c-303942bd81ec.png">

# Proposed Solution
- The header and footer should match, so the background color of the footer and the text color should be updated to use the same blue and white color scheme.
- When dark mode is toggled, ideally the text color in the footer shouldn't change. This should be a small adjustment to the CSS for the toggle.

**Comment by yahya-cloud** [comment]
Hi @marcnjaramillo i would love to work on this

**Comment by pSN0W** [comment]
I will like to work on this issue
