### ISSUE TITLE
Update header and navbar for consistency of styles

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/pod-22.P3.2-portfolio#39]
# Problem
The header on load vs when scroll is activated has two very different appearances:

<img width="1440" alt="Screen Shot 2022-04-06 at 11 39 10 PM" src="https://user-images.githubusercontent.com/18270672/162136060-33703727-0172-4186-8af9-2c2999cf6acc.png">

<img width="1435" alt="Screen Shot 2022-04-06 at 11 39 20 PM" src="https://user-images.githubusercontent.com/18270672/162136081-ae07c552-14e6-4d5c-a844-b932839fca7a.png">

This doesn't really feel like good UI, so there should be some changes.

# Proposed Solution
- The navbar should always be present, with the exception of small screens where it should be hidden under a menu icon ("hamburger" icon).
- I recommend keeping the scroll style but updating the background color to be the original blue. This will help to ensure the project maintains its professional appearance while providing a consistent UX.

**Comment by RishiDesai17** [comment]
@marcnjaramillo The original issue stated that the logo should be moved to the left on scrolling slightly down, If we always have the nav items displayed, then in the future we might run out of space when new nav items are added, since the logo is at the centre when we are at the top of the page.

About the color changing effect, i dont mind removing the transition to black. I had created this since earlier the header was of blue background, so to differentiate the sticky navbar from the header upon scrolling i added the transition.

**Comment by marcnjaramillo** [comment]
> The original issue stated that the logo should be moved to the left on scrolling slightly down

I'm not entirely sure why the original issue was written this way, but from a UX perspective I don't think this is the best way to handle things. As a user, I would want to be able to navigate without having to scroll first. It's also a bit jarring to see the log shift so suddenly and for a navbar to suddenly appear. There is also the issue of accessibility: what is the impact of not having a visible navbar for users who rely on screen readers?

>  If we always have the nav items displayed, then in the future we might run out of space when new nav items are added, since the logo is at the centre when we are at the top of the page.

This is why I suggested keeping the scroll style so the logo is always on the left. As far as space is concerned, the project is fairly simple so there shouldn't be many more items that would be needed. The text could also be decreased in size slightly to accommodate a few more items.

**Comment by RishiDesai17** [comment]
@marcnjaramillo  if we are always keeping the logo on the left, then the new nav items won't cause problems with that. I'll make these changes. Thanks!
