### ISSUE TITLE
Header image change with theme toggle 

### ISSUE THREAD

**Issue by yahya-cloud** [MLH-Fellowship/pod-22.P3.2-portfolio#42]
Header background image could change based on which mode the user sets. So a bright daytime image for light mode and a nighttime image for dark mode.

**Comment by yahya-cloud** [comment]
Hey @marcnjaramillo, i would love to work on this.

**Comment by yahya-cloud** [comment]
Hey @marcnjaramillo, me and @RishiDesai17 would love to work on this.

**Comment by marcnjaramillo** [comment]
Go for it!

**Comment by RishiDesai17** [comment]
The PR for this has been merged, we can close this issue
