### ISSUE TITLE
Individual Project Details Page color issue

### ISSUE THREAD

**Issue by arteevraina** [MLH-Fellowship/pod-22.P3.2-portfolio#46]
If in dark mode, the color of text does not change in Project Detail Page. 

# Screenshot
![image](https://user-images.githubusercontent.com/43968121/162363379-3ef134d9-8b3a-4532-b14c-56ac503d957d.png)

## Link
https://prep-22-p3-2.netlify.app/projects/project

**Comment by judytafilipkowska** [comment]
i will work on it
