### ISSUE TITLE
Footer text color not changing in light mode 

### ISSUE THREAD

**Issue by prakharrathi25** [MLH-Fellowship/pod-22.P3.2-portfolio#47]
The color of the text in the footer remains white even in light mode and makes it impossible to read. 

<img width="630" alt="image" src="https://user-images.githubusercontent.com/38958532/162405868-c9904052-a5a8-49a2-ba1b-6f0c763c73c5.png">

**Comment by prakharrathi25** [comment]
I can work on this one today.

**Comment by judytafilipkowska** [comment]
let's change the background color instead as suggested by Marc
