### ISSUE TITLE
Header issues on individual pages

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/pod-22.P3.2-portfolio#60]
The light/dark mode toggle button is absent on individual project and blog pages, and on the profile pages it is present but the mobile navigation icon is overlapping it:

<img width="298" alt="Screen Shot 2022-04-11 at 8 48 38 AM" src="https://user-images.githubusercontent.com/18270672/162783206-a587bf93-bcaa-460e-a0ae-b15272919269.png">

<img width="300" alt="Screen Shot 2022-04-11 at 8 48 50 AM" src="https://user-images.githubusercontent.com/18270672/162783210-ac2ef325-0d3c-46d2-a31b-8ce0a2bb5923.png">

I believe users should be able to toggle between light and dark mode even on individual pages, so I suggest making sure the toggle button is present on blog, profile, and project pages. Additionally, the mobile nav icon should not be present on these pages since there is no navbar needed on individual pages.

**Comment by RishiDesai17** [comment]
@marcnjaramillo Works fine for me on Chrome. Which browser did you observe this on? Need to look into why we are observing different behaviour
![image](https://user-images.githubusercontent.com/51089917/162781930-545b24dd-982b-45d9-b1ed-4fa745f7a87a.png)
![image](https://user-images.githubusercontent.com/51089917/162781987-b5c18c1b-26d4-4570-ab8a-e0dc5ad31b50.png)

**Comment by RishiDesai17** [comment]
@marcnjaramillo
[!image](https://user-images.githubusercontent.com/51089917/162781930-545b24dd-982b-45d9-b1ed-4fa745f7a87a.png)[](https://user-images.githubusercontent.com/51089917/162781987-b5c18c1b-26d4-4570-ab8a-e0dc5ad31b50.png) Works fine for me on Chrome. Which browser did you observe this on? Need to look into why we are observing different behaviour
image
image

**Comment by marcnjaramillo** [comment]
Hi Rishi, please read my comment carefully. The issue isn't on the homepage; it's on the profile page for individual fellows.

**Comment by RishiDesai17** [comment]
@marcnjaramillo Ohh I am sorry, I'll get this fixed!

**Comment by marcnjaramillo** [comment]
Great! I've assigned it to you @RishiDesai17
