### ISSUE TITLE
Add pod blog

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-22.P3.2-portfolio#7]
It would be awesome to add a blog feature to this repository where fellows can share their insights and people can tune in!

**Comment by prakharrathi25** [comment]
I would like to work on this. Feel free to collaborate if you have ideas for this!

**Comment by RishiDesai17** [comment]
If we want to build a blog in this, then we would need to make a quick backend + DB for it. or have I not understood this issue?

**Comment by prakharrathi25** [comment]
I think we can manage it without a backend since it's a simple Jekyll site. We can just add the blog details in the jekyll file and display it from there.

**Comment by arteevraina** [comment]
I agree with @prakharrathi25 . I think for this issue we should proceed with the data from yaml files just like project details and regarding the backend  + DB we can create a new issue for that.
